# Generated by Django 3.1.5 on 2021-01-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Everegis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=300)),
                ('fromdate', models.DateTimeField()),
                ('todatee', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('hostmail', models.DateTimeField()),
                ('hostPassword', models.CharField(max_length=10)),
            ],
        ),
    ]
