# Generated by Django 3.1.5 on 2021-01-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210112_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disp',
        ),
        migrations.DeleteModel(
            name='Newdate',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
