# Generated by Django 3.1.5 on 2021-01-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='people',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
