# Generated by Django 3.1.5 on 2021-01-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210123_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='people',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='participants',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
