# Generated by Django 3.1.5 on 2021-01-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210124_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='eventype',
            field=models.IntegerField(),
        ),
    ]
